// Code generated by mockery v2.16.0. DO NOT EDIT.

package biz

import (
	contextx "github.com/blackhorseya/ethscan/pkg/contextx"
	blockmodel "github.com/blackhorseya/ethscan/pkg/entity/domain/block/model"

	mock "github.com/stretchr/testify/mock"

	model "github.com/blackhorseya/ethscan/pkg/entity/domain/activity/model"
)

// MockIBiz is an autogenerated mock type for the IBiz type
type MockIBiz struct {
	mock.Mock
}

// GetByHash provides a mock function with given fields: ctx, hash
func (_m *MockIBiz) GetByHash(ctx contextx.Contextx, hash string) (*model.Transaction, error) {
	ret := _m.Called(ctx, hash)

	var r0 *model.Transaction
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) *model.Transaction); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleNewBlock provides a mock function with given fields: ctx, record
func (_m *MockIBiz) HandleNewBlock(ctx contextx.Contextx, record *blockmodel.BlockRecord) ([]*model.Transaction, error) {
	ret := _m.Called(ctx, record)

	var r0 []*model.Transaction
	if rf, ok := ret.Get(0).(func(contextx.Contextx, *blockmodel.BlockRecord) []*model.Transaction); ok {
		r0 = rf(ctx, record)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, *blockmodel.BlockRecord) error); ok {
		r1 = rf(ctx, record)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTxns provides a mock function with given fields: ctx, cond
func (_m *MockIBiz) ListTxns(ctx contextx.Contextx, cond ListTxnsCondition) ([]*model.Transaction, error) {
	ret := _m.Called(ctx, cond)

	var r0 []*model.Transaction
	if rf, ok := ret.Get(0).(func(contextx.Contextx, ListTxnsCondition) []*model.Transaction); ok {
		r0 = rf(ctx, cond)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, ListTxnsCondition) error); ok {
		r1 = rf(ctx, cond)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockIBiz interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIBiz creates a new instance of MockIBiz. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIBiz(t mockConstructorTestingTNewMockIBiz) *MockIBiz {
	mock := &MockIBiz{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
