// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo

import (
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func CreateRepo(opts *NodeOptions, rw *sqlx.DB) (IRepo, error) {
	iRepo, err := NewImpl(opts, rw)
	if err != nil {
		return nil, err
	}
	return iRepo, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
