cronjob:
  enabled: true
  interval: 1s
  needDepth: 32

db:
  url: "root:changeme@tcp(localhost:3306)/portto_block?charset=utf8mb4&parseTime=True&loc=Local"
  debug: true
  conns: 100

node:
  baseURL: "<BASE_URL>"
