// Code generated by mockery v2.16.0. DO NOT EDIT.

package model

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockServiceClient is an autogenerated mock type for the ServiceClient type
type MockServiceClient struct {
	mock.Mock
}

// ListTxnsByBlockHash provides a mock function with given fields: ctx, in, opts
func (_m *MockServiceClient) ListTxnsByBlockHash(ctx context.Context, in *ListTxnsByBlockHashRequest, opts ...grpc.CallOption) (*ListTxnsByBlockHashResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *ListTxnsByBlockHashResponse
	if rf, ok := ret.Get(0).(func(context.Context, *ListTxnsByBlockHashRequest, ...grpc.CallOption) *ListTxnsByBlockHashResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListTxnsByBlockHashResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *ListTxnsByBlockHashRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockServiceClient creates a new instance of MockServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockServiceClient(t mockConstructorTestingTNewMockServiceClient) *MockServiceClient {
	mock := &MockServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
