// Code generated by mockery v2.15.0. DO NOT EDIT.

package model

import mock "github.com/stretchr/testify/mock"

// MockUnsafeServiceServer is an autogenerated mock type for the UnsafeServiceServer type
type MockUnsafeServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedServiceServer provides a mock function with given fields:
func (_m *MockUnsafeServiceServer) mustEmbedUnimplementedServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewMockUnsafeServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeServiceServer creates a new instance of MockUnsafeServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeServiceServer(t mockConstructorTestingTNewMockUnsafeServiceServer) *MockUnsafeServiceServer {
	mock := &MockUnsafeServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
