// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ActivityServiceClient is the client API for ActivityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityServiceClient interface {
	ListTxnsByBlockHash(ctx context.Context, in *ListTxnsByBlockHashRequest, opts ...grpc.CallOption) (*ListTxnsByBlockHashResponse, error)
}

type activityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityServiceClient(cc grpc.ClientConnInterface) ActivityServiceClient {
	return &activityServiceClient{cc}
}

func (c *activityServiceClient) ListTxnsByBlockHash(ctx context.Context, in *ListTxnsByBlockHashRequest, opts ...grpc.CallOption) (*ListTxnsByBlockHashResponse, error) {
	out := new(ListTxnsByBlockHashResponse)
	err := c.cc.Invoke(ctx, "/activity.ActivityService/ListTxnsByBlockHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServiceServer is the server API for ActivityService service.
// All implementations should embed UnimplementedActivityServiceServer
// for forward compatibility
type ActivityServiceServer interface {
	ListTxnsByBlockHash(context.Context, *ListTxnsByBlockHashRequest) (*ListTxnsByBlockHashResponse, error)
}

// UnimplementedActivityServiceServer should be embedded to have forward compatible implementations.
type UnimplementedActivityServiceServer struct {
}

func (UnimplementedActivityServiceServer) ListTxnsByBlockHash(context.Context, *ListTxnsByBlockHashRequest) (*ListTxnsByBlockHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTxnsByBlockHash not implemented")
}

// UnsafeActivityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityServiceServer will
// result in compilation errors.
type UnsafeActivityServiceServer interface {
	mustEmbedUnimplementedActivityServiceServer()
}

func RegisterActivityServiceServer(s grpc.ServiceRegistrar, srv ActivityServiceServer) {
	s.RegisterService(&ActivityService_ServiceDesc, srv)
}

func _ActivityService_ListTxnsByBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTxnsByBlockHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).ListTxnsByBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/activity.ActivityService/ListTxnsByBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).ListTxnsByBlockHash(ctx, req.(*ListTxnsByBlockHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityService_ServiceDesc is the grpc.ServiceDesc for ActivityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "activity.ActivityService",
	HandlerType: (*ActivityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTxnsByBlockHash",
			Handler:    _ActivityService_ListTxnsByBlockHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/activity/model/transaction.proto",
}
