// Code generated by mockery v2.15.0. DO NOT EDIT.

package biz

import (
	contextx "github.com/blackhorseya/portto/pkg/contextx"
	mock "github.com/stretchr/testify/mock"

	model "github.com/blackhorseya/portto/pkg/entity/domain/block/model"
)

// MockIBiz is an autogenerated mock type for the IBiz type
type MockIBiz struct {
	mock.Mock
}

// GetByHash provides a mock function with given fields: ctx, hash
func (_m *MockIBiz) GetByHash(ctx contextx.Contextx, hash string) (*model.BlockRecord, error) {
	ret := _m.Called(ctx, hash)

	var r0 *model.BlockRecord
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) *model.BlockRecord); ok {
		r0 = rf(ctx, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BlockRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, string) error); ok {
		r1 = rf(ctx, hash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, cond
func (_m *MockIBiz) List(ctx contextx.Contextx, cond ListCondition) ([]*model.BlockRecord, error) {
	ret := _m.Called(ctx, cond)

	var r0 []*model.BlockRecord
	if rf, ok := ret.Get(0).(func(contextx.Contextx, ListCondition) []*model.BlockRecord); ok {
		r0 = rf(ctx, cond)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.BlockRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, ListCondition) error); ok {
		r1 = rf(ctx, cond)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScanByHeight provides a mock function with given fields: ctx, height
func (_m *MockIBiz) ScanByHeight(ctx contextx.Contextx, height uint64) (*model.BlockRecord, bool, error) {
	ret := _m.Called(ctx, height)

	var r0 *model.BlockRecord
	if rf, ok := ret.Get(0).(func(contextx.Contextx, uint64) *model.BlockRecord); ok {
		r0 = rf(ctx, height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BlockRecord)
		}
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func(contextx.Contextx, uint64) bool); ok {
		r1 = rf(ctx, height)
	} else {
		r1 = ret.Get(1).(bool)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(contextx.Contextx, uint64) error); ok {
		r2 = rf(ctx, height)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type mockConstructorTestingTNewMockIBiz interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIBiz creates a new instance of MockIBiz. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIBiz(t mockConstructorTestingTNewMockIBiz) *MockIBiz {
	mock := &MockIBiz{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
