// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/portto/internal/pkg/config"
	"github.com/blackhorseya/portto/internal/pkg/log"
	"github.com/blackhorseya/portto/internal/pkg/storage/mariadb"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateService(path2 string, initHeight2 uint64) (*Service, error) {
	viper, err := config.NewConfig(path2)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(options)
	if err != nil {
		return nil, err
	}
	mainOptions, err := NewCronjobOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	cronjob := NewCronjob(mainOptions, logger, initHeight2)
	service, err := NewService(logger, cronjob)
	if err != nil {
		return nil, err
	}
	return service, nil
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, log.ProviderSet, mariadb.ProviderSet, NewService,
	NewCronjobOptions,
	NewCronjob,
)
