// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	"github.com/blackhorseya/ethscan/internal/entity/domain/block/biz/repo"
	"github.com/blackhorseya/ethscan/pkg/entity/domain/activity/model"
	"github.com/blackhorseya/ethscan/pkg/entity/domain/block/biz"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateBiz(repo2 repo.IRepo, activity model.ServiceClient) biz.IBiz {
	iBiz := NewImpl(repo2, activity)
	return iBiz
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
