// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/ethscan/internal/app/domain/activity/biz"
	"github.com/blackhorseya/ethscan/internal/app/domain/activity/biz/repo"
	"github.com/blackhorseya/ethscan/internal/pkg/config"
	"github.com/blackhorseya/ethscan/internal/pkg/log"
	"github.com/blackhorseya/ethscan/internal/pkg/transports/kafka"
	"github.com/blackhorseya/ethscan/pkg/app"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateService(path2 string, id int64) (app.Service, error) {
	viper, err := config.NewConfig(path2)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(options)
	if err != nil {
		return nil, err
	}
	consumerOptions, err := kafka.NewConsumerOptions(viper)
	if err != nil {
		return nil, err
	}
	consumer, err := kafka.NewConsumer(consumerOptions)
	if err != nil {
		return nil, err
	}
	iRepo := repo.NewImpl()
	iBiz := biz.NewImpl(iRepo)
	adaptersKafka := NewKafka(logger, consumer, iBiz)
	service, err := NewService(logger, adaptersKafka)
	if err != nil {
		return nil, err
	}
	return service, nil
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, log.ProviderSet, kafka.ProviderConsumer, biz.ProviderSet, NewService,
	NewKafka,
)
