// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/portto/internal/app/domain/activity/biz"
	"github.com/blackhorseya/portto/internal/app/domain/activity/biz/repo"
	"github.com/blackhorseya/portto/internal/pkg/config"
	"github.com/blackhorseya/portto/internal/pkg/log"
	"github.com/blackhorseya/portto/internal/pkg/storage/mariadb"
	"github.com/blackhorseya/portto/internal/pkg/transports/httpx"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateService(path2 string, id int64) (*Service, error) {
	viper, err := config.NewConfig(path2)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(options)
	if err != nil {
		return nil, err
	}
	httpxOptions, err := httpx.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	engine := httpx.NewRouter(httpxOptions)
	server := httpx.NewServer(httpxOptions, logger, engine)
	iRepo := repo.NewImpl()
	iBiz := biz.NewImpl(iRepo)
	adaptersRestful := NewRestful(logger, engine, iBiz)
	service, err := NewService(logger, server, adaptersRestful)
	if err != nil {
		return nil, err
	}
	return service, nil
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, log.ProviderSet, mariadb.ProviderSet, httpx.ProviderServerSet, biz.ProviderSet, NewService,
	NewRestful,
)
