apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ethscan.fullname" . }}-cm
  labels:
    {{- include "ethscan.labels" . | nindent 4}}
data:
  configs.yaml: |-
{{- if .Values.conf }}
{{ tpl .Values.conf . | indent 4 }}
{{- end }}